id: A01B8555E
title: Prayer for the Land of Great Bliss Practice
type: translation
pechas:
- I37CBBC95
- I3C6E1244
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:46:08.020867
  last_modified_at: 2023-01-04 12:46:08.020888
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  I37CBBC95/C4E7: '4546'
  I3C6E1244/DBEE: '4546'
